version: "3.8"
services:
  backend:
    build: ./backend
    container_name: panoptic-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: panoptic-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - VITE_BACKEND_URL=http://<YOUR_EC2_IP>:8000
    depends_on:
      - backend
